import Details from "@/modules/Blog";
import React from "react";

// Metadata function for Next.js
export const generateMetadata = async ({ params }) => {
  // Await the promise to resolve if it's asynchronous
  const { link } = params;

  // Log the params after they're resolved
  console.log("🚀 ~ metadata ~ params:", params);

  return {
    title: `${link}`, // Dynamic title based on params
    description: "Generated by create-next-app Reviews",
    openGraph: {
      title: `${link}`,
      description: "Description of the Review page",
      type: "website",
    },
  };
};

// Page component
const Page = ({ params }) => {
  console.log("🚀 ~ Page ~ params:", params);

  return (
    <div>
      {/* Passing blogId as a prop to Details */}
      <Details blogId={params.link} />
    </div>
  );
};

export default Page;
