import Details from "@/modules/Blog";
import React from "react";

// Metadata function for Next.js
export const metadata = ({ params }) => {
  return {
    title: `Reviews - ${params.link}`, // Assuming 'link' is the relevant property in 'params'
    description: "Generated by create-next-app Reviews",
    openGraph: {
      title: `Review Page - ${params.link}`, // Adjust title here as needed
      description: "Description of the Review page",
      // image: 'https://yourwebsite.com/path-to-image.jpg',
      // url: 'https://yourwebsite.com/review',
      type: "website",
    },
  };
};

// Page component
const Page = ({ params }) => {
  console.log("🚀 ~ Page ~ params:", params);

  return (
    <div>
      {/* Passing blogId as a prop to Details */}
      <Details blogId={params.link} />
    </div>
  );
};

export default Page;
